BEGIN;

DROP TABLE IF EXISTS delivery_items;
DROP TABLE IF EXISTS deliveries;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS partners;

CREATE TABLE partners (
    partner_id    INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    company_name  VARCHAR(200) NOT NULL,
    inn           VARCHAR(12) NOT NULL,
    contact_email VARCHAR(254) NOT NULL,
    phone         VARCHAR(16),
    rating        DECIMAL(12,1),
    partner_type  VARCHAR(10) NOT NULL DEFAULT '',
    address       VARCHAR(500) NOT NULL DEFAULT '',
    director_name VARCHAR(200) NOT NULL DEFAULT '',

    CONSTRAINT pk_partners PRIMARY KEY (partner_id),
    CONSTRAINT uq_partners_inn UNIQUE (inn),
    CONSTRAINT uq_partners_contact_email UNIQUE (contact_email),
    CONSTRAINT ck_partners_id_positive CHECK (partner_id > 0),
    CONSTRAINT ck_partners_company_name CHECK (
        company_name = btrim(company_name) AND company_name <> ''
    ),
    
    CONSTRAINT ck_partners_inn_format CHECK (inn ~ '^([0-9]{10}|[0-9]{12})$'),
    -- Email хранится в нижнем регистре: UNIQUE исключает дубликаты регистра.
    -- Базовая проверка формы адреса; она не доказывает существование ящика.
    CONSTRAINT ck_partners_email_format CHECK (
        contact_email = lower(btrim(contact_email))
        AND contact_email ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
    ),
    CONSTRAINT ck_partners_phone_format CHECK (
        phone IS NULL OR phone ~ '^\+[1-9][0-9]{7,14}$'
    ),
    
    CONSTRAINT ck_partners_rating CHECK (rating IS NULL OR rating BETWEEN 0 AND 2147483647),
    CONSTRAINT ck_partners_type CHECK (
        partner_type IN ('', 'ЗАО', 'ООО', 'ИП', 'АО', 'ПАО', 'ОАО', 'ТК')
    )
);

CREATE TABLE products (
    product_id   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_name VARCHAR(200) NOT NULL,

    CONSTRAINT pk_products PRIMARY KEY (product_id),
    CONSTRAINT uq_products_product_name UNIQUE (product_name),
    CONSTRAINT ck_products_id_positive CHECK (product_id > 0),
    CONSTRAINT ck_products_product_name CHECK (
        product_name = btrim(product_name) AND product_name <> ''
    )
);

CREATE TABLE deliveries (
    delivery_id   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    partner_id    INT NOT NULL,
    delivery_date DATE NOT NULL,

    CONSTRAINT pk_deliveries PRIMARY KEY (delivery_id),
    CONSTRAINT ck_deliveries_id_positive CHECK (delivery_id > 0),
    CONSTRAINT fk_deliveries_partner FOREIGN KEY (partner_id)
        REFERENCES partners (partner_id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE delivery_items (
    delivery_id INT NOT NULL,
    line_number INT NOT NULL,
    product_id  INT NOT NULL,
    quantity    INT NOT NULL,
    unit_price  DECIMAL(14,4) NOT NULL,

    CONSTRAINT pk_delivery_items PRIMARY KEY (delivery_id, line_number),
    CONSTRAINT fk_delivery_items_delivery FOREIGN KEY (delivery_id)
        REFERENCES deliveries (delivery_id)
        ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_delivery_items_product FOREIGN KEY (product_id)
        REFERENCES products (product_id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_delivery_items_line_number CHECK (line_number > 0),
    CONSTRAINT ck_delivery_items_quantity CHECK (quantity > 0),
    CONSTRAINT ck_delivery_items_unit_price CHECK (unit_price >= 0)
);

CREATE INDEX ix_deliveries_partner_date ON deliveries (partner_id, delivery_date);
CREATE INDEX ix_delivery_items_product ON delivery_items (product_id);

COMMENT ON TABLE partners IS 'Партнеры; редактирование карточки не изменяет отгрузки';
COMMENT ON TABLE products IS 'Уникальные наименования товаров из исходных файлов';
COMMENT ON TABLE deliveries IS 'Заголовки отгрузок; при импорте delivery_id = sale_id';
COMMENT ON TABLE delivery_items IS 'Позиции отгрузок; количество в штуках и цена на дату сделки';
COMMENT ON COLUMN delivery_items.unit_price IS
    'Цена за штуку. Четыре знака сохраняют 18000.50 / 200 = 90.0025 точно';

COMMIT;
